### ISSUE TITLE
loopback-connector-couchdb2@1.0.3 breaks current master

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-connector-cloudant#180]
# Description/Steps to reproduce

Test fails on master:
```
  1 failing

  1) using _id as id "before all" hook:
     Error: Encountered a conflict while saving the design document.
      at node_modules/cloudant/node_modules/cloudant-nano/lib/nano.js:248:15
      at node_modules/cloudant/plugins/retry.js:76:7
      at node_modules/cloudant/node_modules/async/dist/async.js:988:16
      at node_modules/cloudant/node_modules/async/dist/async.js:3118:18
      at apply (node_modules/cloudant/node_modules/async/dist/async.js:41:25)
      at node_modules/cloudant/node_modules/async/dist/async.js:76:12
      at Request._callback (node_modules/cloudant/plugins/retry.js:54:11)
      at Request.self.callback (node_modules/cloudant/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/cloudant/node_modules/request/request.js:1060:10)
      at IncomingMessage.<anonymous> (node_modules/cloudant/node_modules/request/request.js:980:12)
      at endReadableNT (_stream_readable.js:923:12)

```

**Comment by kjdelisle** [comment]
This looks like it was a transient issue, closing.
