### ISSUE TITLE
Error: Invalid operator: $regex

### ISSUE THREAD

**Issue by htammen** [strongloop/loopback-connector-cloudant#20]
I get the following error when calling a _find with regex via my loopback application. When using the in-memory database instead of Cloudant everything works fine.

Regards Helmut

```
_datasource:node_logs:1457390961693, source:node-js-console, _writetime:06/14/16 19:21:41:821 +0000, severity:I 
datetime=2016-06-14T19:21:33.787 +0000,,message=[2016-06-14 19:21:33.786] [ERROR] console - { [Error: Invalid operator: $regex]
  name: 'Error',
  error: 'invalid_operator',
  reason: 'Invalid operator: $regex',
  scope: 'couch',
  statusCode: 400,
  request: 
   { method: 'post',
     headers: 
      { 'content-type': 'application/json',
        accept: 'application/json' },
     uri: 'https://XXXXXX:XXXXXX@yyyyy-yyyyy-yyyy-yyyyy-yyyyy-bluemix.cloudant.com/n-odata-server-example-db/_find">https://XXXXXX:XXXXXX@yyyyy-yyyyy-yyyy-yyyyy-yyyyy-bluemix.cloudant.com/n-odata-server-example-db/_find',
     body: '{"selector":{"loopback__model__name":"BusinessTrip","Location":{"$regex":{}}},"use_index":["lb-index-ddoc-BusinessTrip","lb-index-BusinessTrip"],"limit":20,"sort":[{"Starttime:string":"desc"}]}' },
  headers: 
   { 'x-couch-request-id': '71dff32505',
     date: 'Tue, 14 Jun 2016 19:21:33 GMT',
     'content-type': 'application/json',
     connection: 'close',
     'cache-control': 'must-revalidate',
     'strict-transport-security': 'max-age=31536000',
     'x-content-type-options': 'nosniff;',
     statusCode: 400,
     uri: 'https://XXXXXX:XXXXXX@yyyyy-yyyyy-yyyy-yyyyy-yyyyy-bluemix.cloudant.com/n-odata-server-example-db/_find' },
  errid: 'non_200',
  description: 'couch returned 400' }
Error: Invalid operator: $regex
    at Request._callback (/home/vcap/app/node_modules/loopback-connector-cloudant/node_modules/cloudant/node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (/home/vcap/app/node_modules/loopback-connector-cloudant/node_modules/cloudant/node_modules/nano/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/vcap/app/node_modules/loopback-connector-cloudant/node_modules/cloudant/node_modules/nano/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/loopback-connector-cloudant/node_modules/cloudant/node_modules/nano/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
,source=node-js-console,severity=I
```

**Comment by jannyHou** [comment]
@htammen do you still run into same error? Could you provide the filter you used? Thanks. We have a bunch of test cases for `$regex` and they all pass.

**Comment by b-admike** [comment]
Steps to verify:
- create basic LB app with model `model1` connected to cloudant datasource.
- create following boot script:
```javascript
'use strict';
module.exports = function(app) {
  var myDs = app.datasources.cldntlocal;
  function createMymodel() {
    myDs.automigrate('model1', function(err) {
      if (err)
        console.error('failed to migrate model-1 ', err);
      else {
        console.log('model created');
        insertModel();
      }
    });
  };
  function insertModel() {
    var myModel = app.models.model1;
    var testModel = {};
    testModel.foo = '123456789';
    var testModel2 = {foo: 'abcdefgh'};
    myModel.create([testModel, testModel2], function(err) {
      if (err)
        console.log('Insert failed ', err);
      else
        console.log('insert successful');
      myModel.find({where: {foo: {regexp: '^a'}}}, function(err, res) {
        if (err)
          console.log('find failed ', err);
        else
        console.log('find matching regexp: ', res);
      });
    });
  };
  myDs.once('connected', createMymodel);
};
```

results:
```
| => node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer
model created
insert successful
find only results:  [ { _rev: '1-b14a0f9ea27028f1d5484da94d79a32d',
    foo: 'abcdefgh',
    id: '22d0f5a08ddaef4e34d8cacdf2014b9f' } ]
^C
```

**Comment by b-admike** [comment]
connect to https://github.com/strongloop-internal/scrum-apex/issues/240
