### ISSUE TITLE
Fix CI - 2 test cases failed

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-connector-cloudant#201]
## Description
There are 2 test cases failed in CI. 
See the results from https://github.com/strongloop/loopback-connector-cloudant/pull/200

```
1) cloudant imported features include does not return included item if FK is excluded:
14:31:38      Uncaught AssertionError: expected Object {
14:31:38   _rev: '1-988efb5445f8b6d5c87bb36d90020332',
14:31:38   age: 21,
14:31:38   id: 'ab7a5b36338b8de50db893d1a3004859',
14:31:38   name: 'User A'
14:31:38 } to not exist
14:31:38       at node_modules/loopback-datasource-juggler/test/include.test.js:53:18
14:31:38       at node_modules/loopback-datasource-juggler/lib/dao.js:1707:9
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1140:9
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:473:16
14:31:38       at iteratorCallback (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1064:13)
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:969:16
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1137:13
14:31:38       at buildResult (node_modules/loopback-datasource-juggler/lib/dao.js:1673:11)
14:31:38       at node_modules/loopback-datasource-juggler/lib/dao.js:1687:13
14:31:38       at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
14:31:38       at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
14:31:38       at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
14:31:38       at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
14:31:38       at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
14:31:38       at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
14:31:38       at withNotify (node_modules/loopback-datasource-juggler/lib/dao.js:1685:17)
14:31:38       at node_modules/loopback-datasource-juggler/lib/dao.js:1626:11
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1135:9
14:31:38       at eachOfArrayLike (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1069:9)
14:31:38       at eachOf (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1117:5)
14:31:38       at _asyncMap (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1133:5)
14:31:38       at Object.map (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1122:16)
14:31:38       at allCb (node_modules/loopback-datasource-juggler/lib/dao.js:1621:13)
14:31:38       at node_modules/loopback-connector-couchdb2/lib/couchdb.js:314:5
14:31:38       at Cloudant.CouchDB._extendDocs (node_modules/loopback-connector-couchdb2/lib/couchdb.js:1104:58)
14:31:38       at node_modules/loopback-connector-couchdb2/lib/couchdb.js:1090:12
14:31:38       at node_modules/loopback-datasource-juggler/lib/include.js:194:11
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:473:16
14:31:38       at iteratorCallback (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1064:13)
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:969:16
14:31:38       at node_modules/loopback-datasource-juggler/lib/include.js:105:11
14:31:38       at _combinedTickCallback (internal/process/next_tick.js:132:7)
14:31:38       at process._tickCallback (internal/process/next_tick.js:181:9)
14:31:38 
14:31:38   2) cloudant imported features include should report errors if the PK is excluded:
14:31:38      Uncaught AssertionError: expected null to exist
14:31:38       at node_modules/loopback-datasource-juggler/test/include.test.js:81:14
14:31:38       at node_modules/loopback-datasource-juggler/lib/dao.js:1707:9
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1140:9
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:473:16
14:31:38       at iteratorCallback (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1064:13)
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:969:16
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1137:13
14:31:38       at buildResult (node_modules/loopback-datasource-juggler/lib/dao.js:1673:11)
14:31:38       at node_modules/loopback-datasource-juggler/lib/dao.js:1687:13
14:31:38       at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
14:31:38       at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
14:31:38       at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
14:31:38       at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
14:31:38       at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
14:31:38       at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
14:31:38       at withNotify (node_modules/loopback-datasource-juggler/lib/dao.js:1685:17)
14:31:38       at node_modules/loopback-datasource-juggler/lib/dao.js:1626:11
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1135:9
14:31:38       at eachOfArrayLike (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1069:9)
14:31:38       at eachOf (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1117:5)
14:31:38       at _asyncMap (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1133:5)
14:31:38       at Object.map (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1122:16)
14:31:38       at allCb (node_modules/loopback-datasource-juggler/lib/dao.js:1621:13)
14:31:38       at node_modules/loopback-connector-couchdb2/lib/couchdb.js:314:5
14:31:38       at Cloudant.CouchDB._extendDocs (node_modules/loopback-connector-couchdb2/lib/couchdb.js:1104:58)
14:31:38       at node_modules/loopback-connector-couchdb2/lib/couchdb.js:1090:12
14:31:38       at node_modules/loopback-datasource-juggler/lib/include.js:194:11
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:473:16
14:31:38       at iteratorCallback (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1064:13)
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:969:16
14:31:38       at targetFetchHandler (node_modules/loopback-datasource-juggler/lib/include.js:635:9)
14:31:38       at node_modules/loopback-datasource-juggler/lib/dao.js:1707:9
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1140:9
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:473:16
14:31:38       at iteratorCallback (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1064:13)
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:969:16
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1137:13
14:31:38       at buildResult (node_modules/loopback-datasource-juggler/lib/dao.js:1673:11)
14:31:38       at node_modules/loopback-datasource-juggler/lib/dao.js:1687:13
14:31:38       at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
14:31:38       at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
14:31:38       at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
14:31:38       at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
14:31:38       at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
14:31:38       at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
14:31:38       at withNotify (node_modules/loopback-datasource-juggler/lib/dao.js:1685:17)
14:31:38       at node_modules/loopback-datasource-juggler/lib/dao.js:1626:11
14:31:38       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1135:9
14:31:38       at eachOfArrayLike (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1069:9)
14:31:38       at eachOf (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1117:5)
14:31:38       at _asyncMap (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1133:5)
14:31:38       at Object.map (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1122:16)
14:31:38       at allCb (node_modules/loopback-datasource-juggler/lib/dao.js:1621:13)
14:31:38       at node_modules/loopback-connector-couchdb2/lib/couchdb.js:314:5
14:31:38       at Cloudant.CouchDB._extendDocs (node_modules/loopback-connector-couchdb2/lib/couchdb.js:1104:58)
14:31:38       at node_modules/loopback-connector-couchdb2/lib/couchdb.js:1090:12
14:31:38       at include (node_modules/loopback-connector-couchdb2/lib/couchdb.js:309:7)
14:31:38       at node_modules/loopback-connector-couchdb2/lib/couchdb.js:1089:5
14:31:38       at Request._callback (node_modules/cloudant-nano/lib/nano.js:217:16)
14:31:38       at Request.self.callback (node_modules/request/request.js:185:22)
14:31:38       at Request.<anonymous> (node_modules/request/request.js:1161:10)
14:31:38       at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
14:31:38       at endReadableNT (_stream_readable.js:1064:12)
14:31:38       at _combinedTickCallback (internal/process/next_tick.js:139:11)
14:31:38       at process._tickCallback (internal/process/next_tick.js:181:9)
14:31:38 
14:31:38 
14:31:38 
14:31:38 cleaning up container: ac3c0d321cd3fa81f31f822864cfc1ed5ef603034c981ed6f924f3270afc0ffd
14:31:39 error running tests: Error: mocha exited with code: 2, sig: null
14:31:39     at ChildProcess.onExit (/home/jenkins/workspace/nb/loopback-connector-cloudant~master/4f443a72/test.js:184:14)
14:31:39     at emitTwo (events.js:126:13)
14:31:39     at ChildProcess.emit (events.js:214:7)
14:31:39     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
14:31:39 
```

## Acceptance Criteria
- [ ] Fix the 2 test cases and make CI green again
       These 2 fixes expose 2 new failures in juggler. A new PR will be created to fix these issues
       and finally allow CI to succeed.

**Comment by dhmlau** [comment]
Also see comment https://github.com/strongloop/loopback-datasource-juggler/pull/1705#issuecomment-480254509

**Comment by dhmlau** [comment]
@jannyHou , assigning this to you since you're working on it. thanks.

**Comment by jannyHou** [comment]
🎉 Fixed after releasing `loopback-connector-couchdb2@1.4.0`, see test PR https://github.com/strongloop/loopback-connector-cloudant/pull/204, CI is green.
I am closing this story.
