### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined loopback-connector-cloudant/lib/cloudant.js:230

### ISSUE THREAD

**Issue by vinodk21** [strongloop/loopback-connector-cloudant#73]
Hi ,

Application is crashing frequently because of the following error. (loopback-connector-cloudant 1.0.11 ). 

ERR /home/vcap/app/node_modules/loopback-connector-cloudant/lib/cloudant.js:230
2017-01-16T15:38:39.42+0530 [App/0]      ERR       for (var i = 0; i < docs.length; i++) {
2017-01-16T15:38:39.42+0530 [App/0]      ERR                               ^
2017-01-16T15:38:39.42+0530 [App/0]      ERR TypeError: Cannot read property 'length' of undefined
2017-01-16T15:38:39.42+0530 [App/0]      ERR     at include (/home/vcap/app/node_modules/loopback-connector-cloudant/lib/cloudant.js:230:31)
2017-01-16T15:38:39.42+0530 [App/0]      ERR     at Request._callback (/home/vcap/app/node_modules/loopback-connector-cloudant/node_modules/cloudant/node_modules/cloudant-nano/lib/nano.js:216:16)
2017-01-16T15:38:39.42+0530 [App/0]      ERR     at Request.self.callback (/home/vcap/app/node_modules/loopback-connector-cloudant/node_modules/cloudant/node_modules/request/request.js:186:22)
2017-01-16T15:38:39.42+0530 [App/0]      ERR     at emitTwo (events.js:87:13)
2017-01-16T15:38:39.42+0530 [App/0]      ERR     at Request.emit (events.js:172:7)
2017-01-16T15:38:39.42+0530 [App/0]      ERR     at emitOne (events.js:77:13)
2017-01-16T15:38:39.42+0530 [App/0]      ERR     at Request.emit (events.js:169:7)
2017-01-16T15:38:39.42+0530 [App/0]      ERR     at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/loopback-connector-cloudant/node_modules/cloudant/node_modules/request/request.js:980:12)
2017-01-16T15:38:39.42+0530 [App/0]      ERR     at IncomingMessage.g (events.js:260:16)
2017-01-16T15:38:39.42+0530 [App/0]      ERR     at emitNone (events.js:72:20)
2017-01-16T15:38:39.42+0530 [App/0]      ERR     at endReadableNT (_stream_readable.js:923:12)
2017-01-16T15:38:39.42+0530 [App/0]      ERR     at /home/vcap/app/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
2017-01-16T15:38:39.42+0530 [App/0]      ERR     at nextTickCallbackWith2Args (node.js:458:9)
2017-01-16T15:38:39.42+0530 [App/0]      ERR     at process._tickDomainCallback (node.js:413:17)
2017-01-16T15:38:39.42+0530 [App/0]      ERR     at process.fallback (/home/vcap/app/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:482:15)

Could you please help

**Comment by dhmlau** [comment]
Hi @vinodk21 , could you please provide more information in reproducing the problem?  e.g. loopback application, or model json?  thanks.

**Comment by 0candy** [comment]
@vinodk21 Could you please update to the latest cloudant connector and try again? Please provide the debug logs if you encounter this issue again.

**Comment by dhmlau** [comment]
The fix has been released in v1.2.2.  Please try again. 

PR: https://github.com/strongloop/loopback-connector-cloudant/pull/87

**Comment by kjdelisle** [comment]
Closing as fixed. Please comment here if v1.2.2 does not resolve the issue.
